name: Deploy Preview on Push to Dev

on:
  push:
    branches:
      - dev  # Runs only when pushing to the dev branch

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Preview Deployment
        run: curl -X POST "${{ secrets.VERCEL_PREVIEW_WEBHOOK }}"
